name: python build and test

on:
  push:
    - main
  pull_request:
    - main
  workflow_dispatch:

jobs:
  build_and_test:
    runs-on: ubuntu-latest 

    steps:
      - name: checkout code
        uses: actions/checkout@v4
      
      - name: setup python
        uses: actions/setup-python@v5 
        with:
          python-version: '3.11'

      - name: Install dependencies 
        run: pip install -r requirements.txt 

      - name: run lint 
        run: flake8 .

      - name: run test
        run: pytest
      
      - name: test completed
        run: echo " tests done"

